#!/bin/sh

# this is for GDM, KDM, LXDE

# start fcitx
if command -v fcitx >/dev/null 2>&1; then
   export XMODIFIERS=@im=fcitx
   export GTK_IM_MODULE=fcitx
   export QT_IM_MODULE=fcitx
   killall -q fcitx
   fcitx &
fi

# Xterm config
if [ -f ~/.Xresources ]; then
    xrdb $HOME/.Xresources
fi

# remap keys
if [ -f ~/.Xmodmap ]; then
    xmodmap $HOME/.Xmodmap
fi

# start emacs daemon
if command -v emacs > /dev/null 2>&1; then
    emacsclient -e "(kill-emacs)"
    emacs --daemon &
fi

# add font dir for xft
xset fp+ $HOME/.fonts &
xset fp rehash
